### ISSUE TITLE
pip installable until SciPy integration? 

### ISSUE THREAD

**Issue by jolespin** [vreyespue/scipy_cut_tree_balanced#1]
I've been following your thread and looking forward to using it.  I'm interested in assisting in a publication as I have lots and lots and lots and lots of data I could benchmark this on.  Unfortunately, I'm not going to be able to get to it until the end of the year at the earliest.  I'm pursuing a PhD where the majority of my dissertation is based on my publications and I have my keystone publications that I'm currently working on. 

I guess my request for this "issue" would be the following:
Generalize `ward_cut_tree_balanced` to `cut_tree_balanced` (I think that's what you mentioned the shortened version would be) and make it installable via `PyPI` (i.e. `pip`).  In the meantime, it can be cited through zenodo to track publications.  ANY alternative to `dynamicCutTree` would be awesome to have at my arsenal.

**Comment by vreyespue** [comment]
Hi @jolespin, I have renamed the function to `cut_tree_balanced`, and updated the documentation. I hope this makes clearer that the method should work with any kind of SciPy linkage matrix, no matter which method was used to create it (being 'ward' just one possible method, see the [documentation of the linkage function](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html).
Please let me know what you think.
Many thanks and best regards.

**Comment by vreyespue** [comment]
Hi @jolespin, about making this package installable vie `PyPI`(i.e. `pip`): I will leave [this PR](https://github.com/scipy/scipy/pull/10730) a last chance to be merged into the SciPy main repo. If this does not happen within the next milestone (1.6.0), I will proceed to close the PR into ScyPy and make the package available through `PyPI`. About Zenodo: that's a very good idea, I will take a look at it as well. Many thanks and best regards.

**Comment by jolespin** [comment]
I lost track of this a bit.  How come it hasn't been merged? Are they awaiting some benchmarking or do they want a publication first?

**Comment by vreyespue** [comment]
Hi @jolespin, it seems that they (the SciPy community) are currently short on reviewer bandwidth, and they are also trying to deal with a problem with one of their CI providers. Thus, they are not waiting for a publication first, the PR review simply takes very long. I will give them some more weeks, and if it doesn't work, then we can go for your proposed solution (i.e. pip + zenodo). Does this sound like a good plan? Many thanks and best regards.

**Comment by jolespin** [comment]
Looking forward to using it in some publications!  I have 3 upcoming for my PhD so I'll try and throw them in there so I can finally reduce my dependency on dynamicTreeCut.

**Comment by vreyespue** [comment]
Hi @jolespin, that sounds great, I hope the method is useful 😄  Please let me know if I can help. Many thanks and best regards.

**Comment by vreyespue** [comment]
Hi @jolespin, as you can see in the Readme I made this repo pip-installable through a PyPI package. In addition (and according to your suggestion), I made it citable via Zenodo. Please let me know if you need further info, otherwise I would proceed to close the present issue. Many thanks and best regards.

**Comment by jolespin** [comment]
Thanks for doing all of that.  It will make it much easier to use a cite. Let's close this issue.
